// script.js

// Data yang diberikan dalam format JSON
const data = [
//KELAS QURAN
{
  "NAMA": "AHMAD DIRJAT ABDALA",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "001"
}, 
{
  "NAMA": "AINA ASYIFA",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "002"
}, 
{
  "NAMA": "ALIFA RAMADHINA",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "005"
}, 
{
  "NAMA": "AMIRAH FIRJATUL",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "007"
}, 
{
  "NAMA": "ARA SALSABILA",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "009"
}, 
{
  "NAMA": "ASSYIFA MAWADDAH",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "010"
}, 
{
  "NAMA": "DIMAS EDRA",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "012"
}, 
{
  "NAMA": "HAFIDZA KHAIRA YUMNA FAHLEVI",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "014"
}, 
{
  "NAMA": "KHALISA SALSABILA",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "016"
}, 
{
  "NAMA": "LUTFIA MUTMAINNAH",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "017"
}, 
{
  "NAMA": "M. FAUZI",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "018"
}, 
{
  "NAMA": "M. RAFI SYAHDILLA",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "019"
}, 
{
  "NAMA": "M. RIZKY",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "020"
}, 
{
  "NAMA": "M. RIZQI YAZID",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "021"
}, 
{
  "NAMA": "MUHAMMAD AUFA RAHMAN",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "023"
}, 
{
  "NAMA": "MUHAMMAD FAIREL ATHARIZZ",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "024"
}, 
{
  "NAMA": "MUHAMMAD NABIL RIADI",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "025"
}, 
{
  "NAMA": "MUHAMMAD SHIDQII FADHILLAH",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "026"
}, 
{
  "NAMA": "MUHAMMAD ZIDAN",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "027"
}, 
{
  "NAMA": "NAYLA RIZKY AMALIA",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "028"
}, 
{
  "NAMA": "NIHAYATUS SHOLIHAH",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "029"
}, 
{
  "NAMA": "NUR AFIFAH ZAIN",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "030"
}, 
{
  "NAMA": "NUR RAHADATUL SYALWA",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "031"
}, 
{
  "NAMA": "RAFLI DAFFA SANTOSO",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "035"
}, 
{
  "NAMA": "REGINA RAHADHATUL AISY",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "036"
}, 
{
  "NAMA": "RIANA AZMI",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "037"
}, 
{
  "NAMA": "SITI NURHAYATUL HASANAH",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "039"
}, 
{
  "NAMA": "TIARA LUTHFIYAH",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "040"
}, 
{
  "NAMA": "ZHAFIRA ZIYADATUL KHAIR",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "041"
}, 
{
  "NAMA": "AFDALIA",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "054"
}, 
{
  "NAMA": "NORMA LINDA EKA PRADELLA",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "485"
}, 
{
  "NAMA": "FADHILA ZAHRA",
  "PEMBIMBING AWAL": "USTADZ FAHRUL",
  "PEMBIMBING BARU": "USTADZ FAHRUL",
  "STATUS": "TAHFIDZ"
}, 
{
  "NAMA": "AKMAL BISMA AJI",
  "PEMBIMBING AWAL": "USTADZ UMAM",
  "PEMBIMBING BARU": "USTADZ UMAM",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "043"
}, 
{
  "NAMA": "ALLISHA ZHAFIRADIVA FAISAL",
  "PEMBIMBING AWAL": "USTADZ UMAM",
  "PEMBIMBING BARU": "USTADZ UMAM",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "044"
}, 
{
  "NAMA": "M. ALI REVAN",
  "PEMBIMBING AWAL": "USTADZ UMAM",
  "PEMBIMBING BARU": "USTADZ UMAM",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "045"
}, 
{
  "NAMA": "MUHAMMAD FAEYZA NAUFAL",
  "PEMBIMBING AWAL": "USTADZ UMAM",
  "PEMBIMBING BARU": "USTADZ UMAM",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "046"
}, 
{
  "NAMA": "MUHAMMAD RAFKA ANWAR",
  "PEMBIMBING AWAL": "USTADZ UMAM",
  "PEMBIMBING BARU": "USTADZ UMAM",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "047"
}, 
{
  "NAMA": "MUHAMMAD SHOLIHIN",
  "PEMBIMBING AWAL": "USTADZ UMAM",
  "PEMBIMBING BARU": "USTADZ UMAM",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "048"
}, 
{
  "NAMA": "NUR VIRDA AYUNDA",
  "PEMBIMBING AWAL": "USTADZ UMAM",
  "PEMBIMBING BARU": "USTADZ UMAM",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "049"
}, 
{
  "NAMA": "SITI AFIQA ARTA AZALIA",
  "PEMBIMBING AWAL": "USTADZ UMAM",
  "PEMBIMBING BARU": "USTADZ UMAM",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "050"
}, 
{
  "NAMA": "SITI ALIYAH",
  "PEMBIMBING AWAL": "USTADZ UMAM",
  "PEMBIMBING BARU": "USTADZ UMAM",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "051"
}, 
{
  "NAMA": "MAHARANI AULIA SUBHAN",
  "PEMBIMBING AWAL": "USTADZ UMAM",
  "PEMBIMBING BARU": "USTADZ UMAM",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "052"
}, 
{
  "NAMA": "ALMATARA KHUMAIRA",
  "PEMBIMBING AWAL": "USTADZ UMAM",
  "PEMBIMBING BARU": "USTADZ UMAM",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "529"
}, 
{
  "NAMA": "ALYA NUR ASYILA",
  "PEMBIMBING AWAL": "USTADZ UMAM",
  "PEMBIMBING BARU": "USTADZ UMAM",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "530"
}, 
{
  "NAMA": "RAQA MAFAZI AGFA",
  "PEMBIMBING AWAL": "USTADZ UMAM",
  "PEMBIMBING BARU": "USTADZ UMAM",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "252"
}, 
{
  "NAMA": "TAMINA NUR ASSYIFA",
  "PEMBIMBING AWAL": "USTADZ UMAM",
  "PEMBIMBING BARU": "USTADZ UMAM",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "249"
}, 
{
  "NAMA": "MUHAMMAD RAFIF IMANSYAH",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "412"
}, 
{
  "NAMA": "MUHAMMAD ADITYA SAPUTRA",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "413"
}, 
{
  "NAMA": "AZKA MAULIDA NURRACHMAH",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "414"
}, 
{
  "NAMA": "RAFFA ATHAYA CISHANDY PUTRI",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "415"
}, 
{
  "NAMA": "MUHAMMAD TIRTA FARSYA UTAMA",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "416"
}, 
{
  "NAMA": "AISYA HUMAIRA (MEMEY)",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "417"
}, 
{
  "NAMA": "ALDANIA PUTRI SILVANA",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "418"
}, 
{
  "NAMA": "FATIMAH SARAH",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "419"
}, 
{
  "NAMA": "M. AS'AD ALI DAROHMAN",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "420"
}, 
{
  "NAMA": "MUHAMMAD HAFI KHOLILURRAHMAN",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "421"
}, 
{
  "NAMA": "MUHAMMAD KHAIRIL AKMAL",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "422"
}, 
{
  "NAMA": "MUHAMMAD KHAIRIL KAFA",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "423"
}, 
{
  "NAMA": "MUHAMMAD NAHRU ROHMAN",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "424"
}, 
{
  "NAMA": "MUHAMMAD SAMMAN",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "425"
}, 
{
  "NAMA": "MUHAMMAD NABHAN AHNAF",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "426"
}, 
{
  "NAMA": "NAFEEZA IQLIMA ANDENI",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "427"
}, 
{
  "NAMA": "KHANSA HUMAIRA",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "428"
}, 
{
  "NAMA": "M. RABBANI FAQIH",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "429"
}, 
{
  "NAMA": "M. RESTU FIRDAUS",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "430"
}, 
{
  "NAMA": "MUHAMMAD DZAKY SIRAJ",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "431"
}, 
{
  "NAMA": "MUHAMMAD NAJIBILKHAIRY",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "432"
}, 
{
  "NAMA": "MUHAMMAD RAHMAN",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "433"
}, 
{
  "NAMA": "MUHAMMAD RAJENDRA RAFAEL",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "434"
}, 
{
  "NAMA": "NOOR AZIZAH",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "435"
}, 
{
  "NAMA": "SYARIFAH FARAH ATHIRA SALSABILA",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "436"
}, 
{
  "NAMA": "ANGGITA AZZAHRA",
  "PEMBIMBING AWAL": "USTADZAH IPAH",
  "PEMBIMBING BARU": "USTADZAH IPAH",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "437"
}, 
{
  "NAMA": "ADITYA DARMA PUTRA",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "438"
}, 
{
  "NAMA": "AHMAD ADIB MUHARRAM",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "439"
}, 
{
  "NAMA": "AKHMAD PUTRA PRATAMA",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "440"
}, 
{
  "NAMA": "AHMAD RAMADANI",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "441"
}, 
{
  "NAMA": "AMIRAH HASNA HAKIMAH",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "443"
}, 
{
  "NAMA": "AYESHA HAYFA MAHIRA",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "444"
}, 
{
  "NAMA": "DAFA RADITIYA",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "445"
}, 
{
  "NAMA": "FATIMAH ZAHRA",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "446"
}, 
{
  "NAMA": "GUSTI HANIF AL KHALIFI",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "447"
}, 
{
  "NAMA": "HERMI MULIA SARI",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "448"
}, 
{
  "NAMA": "KURNIAWATI",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "449"
}, 
{
  "NAMA": "MUHAMMAD  ZAKY AL FATIH",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "450"
}, 
{
  "NAMA": "MUHAMMAD  INSYIRA RAMADHAN",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "451"
}, 
{
  "NAMA": "MUHAMMAD  RIFA'I",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "452"
}, 
{
  "NAMA": "MUHAMMAD  YAZID",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "453"
}, 
{
  "NAMA": "M. HAFIDZ RAMADANISH",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "157"
}, 
{
  "NAMA": "HAIQAL FAIZ",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "161"
}, 
{
  "NAMA": "MUHAMMAD ABID JAUHAIR",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "189"
}, 
{
  "NAMA": "MARITZA SABRINA HAMIZA",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "190"
}, 
{
  "NAMA": "SITI ZAGIA GATI RAMADHANA",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "193"
}, 
{
  "NAMA": "MUHAMMAD ALKHALIFI ZIKRI HADY",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "196"
}, 
{
  "NAMA": "AHMAD ZIO ZAVIER AZZAM",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "214"
}, 
{
  "NAMA": "ATIFA AYUDYHA HASAN",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "216"
}, 
{
  "NAMA": "M. YUSUF HAMDANI",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "217"
}, 
{
  "NAMA": "AHMAD SYAMIL KHAIRAN",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "218"
}, 
{
  "NAMA": "ANNIDA ZAHRATUNNISA",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "220"
}, 
{
  "NAMA": "AISHA NUR ZAHIRA",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "222"
}, 
{
  "NAMA": "HAIDIR MUARAS",
  "PEMBIMBING AWAL": "USTADZ SOFYAN",
  "PEMBIMBING BARU": "USTADZ SOFYAN",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "225"
}, 
{
  "NAMA": "FAIRA MEHRUNISA",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "138"
}, 
{
  "NAMA": "AHMAD FAKHRI AKBAR",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "139"
}, 
{
  "NAMA": "M.HANAN AL FAIZ",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "140"
}, 
{
  "NAMA": "NAYSYILA AZIZAH",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "141"
}, 
{
  "NAMA": "M. DAFFA RAHMAN",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "142"
}, 
{
  "NAMA": "NAFIATUL NAFISAH",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "143"
}, 
{
  "NAMA": "RIZKI AUFAR OKTAVIAN",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "144"
}, 
{
  "NAMA": "SYAILLA NAMIRA",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "145"
},  
{
  "NAMA": "M. AFIF NAWABIGHNA",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "147"
}, 
{
  "NAMA": "NUR ZAHIDAH ZULFA",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "148"
}, 
{
  "NAMA": "MUHAMMAD ZAKY MIRZA",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "149"
}, 
{
  "NAMA": "MUHAMMAD ARYA PRATAMA",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "150"
}, 
{
  "NAMA": "ZAITUN NISA",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "53"
}, 
{
  "NAMA": "AZZILA KHAIRUNNISA",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "151"
}, 
{
  "NAMA": "LATISHA PRAMESTI BUDIONO",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "152"
}, 
{
  "NAMA": "M. AZKA ALFARO",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "155"
}, 
{
  "NAMA": "MUHAMMAD AZKA NAZHAN",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "158"
}, 
{
  "NAMA": "M. NASYID HAIKAL",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "159"
}, 
{
  "NAMA": "YUMNA GITA KINANTI",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "160"
},  
{
  "NAMA": "RAISA AQILA PUTRI",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "201"
}, 
{
  "NAMA": "NIA NUR RAMADHANI",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ UMAM",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "235"
}, 
{
  "NAMA": "RIZKA RAMADHANI",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "237"
}, 
{
  "NAMA": "SOFIATUS ZAHRA",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "528"
}, 
{
  "NAMA": "LULU AZKIA ZIDNIE",
  "PEMBIMBING AWAL": "USTADZ HUSSAINI",
  "PEMBIMBING BARU": "USTADZ HUSSAINI",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "527"
}, 
{
  "NAMA": "⁠NADILA PUTRI HALIMAH",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "488"
}, 
{
  "NAMA": "M. FAIZ IRAWAN",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "533"
}, 
{
  "NAMA": "M. ALIF YAHSAN",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "156"
}, 
{
  "NAMA": "MUHAMMAD FATHIR ABIYYU",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "186"
}, 
{
  "NAMA": "AZZAHRA MAISOUPA",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "213"
}, 
{
  "NAMA": "ALISHA RANIA AZZAHRA",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "215"
}, 
{
  "NAMA": "NOOR AQILA FATIMAH",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "219"
}, 
{
  "NAMA": "FAHMA AHNAN",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "223"
}, 
{
  "NAMA": "M. MULTAZAM",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "224"
}, 
{
  "NAMA": "NAZWA FAIRUZ",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "226"
}, 
{
  "NAMA": "MUHAMMAD SAMMAN AL MADANI",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "229"
}, 
{
  "NAMA": "RIZQY NABILA ALMERA",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "230"
}, 
{
  "NAMA": "MUHAMMAD SALMAN ALFHARIZHI",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "234"
}, 
{
  "NAMA": "MUHAMMAD ULIL ALBAB",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "241"
}, 
{
  "NAMA": "M. ARKAN RAMADHAN",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "153"
}, 
{
  "NAMA": "MUHAMMAD FAJAR",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "166"
}, 
{
  "NAMA": "MUHAMMAD GILANG PRATAMA",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "182"
}, 
{
  "NAMA": "ISMAH NUR RAMADHANI",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "185"
}, 
{
  "NAMA": "MUHAMMAD GHANI HANAFI",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "187"
}, 
{
  "NAMA": "MUHAMMAD AYLABY FATHORY",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "191"
}, 
{
  "NAMA": "MIRANDA",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "192"
}, 
{
  "NAMA": "MUHAMMAD RAFIF AL FARAZ",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "198"
}, 
{
  "NAMA": "RAISA NADHIFA CISHANDY PUTRI",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "199"
}, 
{
  "NAMA": "ZHARFAN EL RAFIF INDAH",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "202"
}, 
{
  "NAMA": "NUR ADELIA SAFITRI",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "251"
}, 
{
  "NAMA": "GUSTI FATHIYA RILLIE HASYAWAZA",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "260"
}, 
{
  "NAMA": "JALALLUDIN AS-SYAYUTI",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "340"
}, 
{
  "NAMA": "MUHAMMAD RASYID RIDHO",
  "PEMBIMBING AWAL": "USTADZAH ASTRID",
  "PEMBIMBING BARU": "USTADZAH ASTRID",
  "STATUS": "JILID QURAN",
  "NOINFAQ": "487"
}, 
{
  "NAMA": "ABIMANYU",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "383"
}, 
{
  "NAMA": "AMALIA NUR RIZQA",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "384"
}, 
{
  "NAMA": "MUHAMMAD AZKA RAQILLA",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "386"
}, 
{
  "NAMA": "NASWA SALSABILA",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "387"
}, 
{
  "NAMA": "PUTRI FATMA ZAHIRA",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "388"
}, 
{
  "NAMA": "SELLYN RIZKI MARSHANTI",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "389"
}, 
{
  "NAMA": "AILUL ZAKI ALFIN",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "390"
}, 
{
  "NAMA": "M. YUSUF MADANI",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "391"
}, 
{
  "NAMA": "NADIYA MAULIDA",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "393"
}, 
{
  "NAMA": "SHAFIRA SALSABILA",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "395"
}, 
{
  "NAMA": "SITI AMIRA NAJMUTSAQIBAH",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "396"
}, 
{
  "NAMA": "MUHAMMAD RIZKY ZAIDAN",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "397"
}, 
{
  "NAMA": "RAKHA NURHAFIDZAN",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "398"
}, 
{
  "NAMA": "M.RIFAT AZIZI RAHMAN",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "399"
}, 
{
  "NAMA": "ALIYA ANISAH",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "401"
}, 
{
  "NAMA": "AYDIN KHALFANI REAGAN",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "410"
}, 
{
  "NAMA": "FINA MAULINA",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "402"
}, 
{
  "NAMA": "LISA AMELIA",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "403"
}, 
{
  "NAMA": "MUHAMMAD ADITYA SAPUTRA",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "413"
}, 
{
  "NAMA": "MUHAMMAD BILAL AL-FATTAAH",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "404"
}, 
{
  "NAMA": "MUHAMMAD DZAKY MAULANA",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "411"
}, 
{
  "NAMA": "NAYLA FAUJIAH",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "406"
}, 
{
  "NAMA": "STEVANNY MARIETA JASA",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "407"
}, 
{
  "NAMA": "ZAHARA ALHENA DINAR",
  "PEMBIMBING AWAL": "USTADZ JUFRI",
  "PEMBIMBING BARU": "USTADZ JUFRI",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "408"
}, 
{
  "NAMA": "FARHAN RASYAD FARANDY",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "098"
}, 
{
  "NAMA": "FAEZA HASAN AZHARI",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "100"
}, 
{
  "NAMA": "GUSTI SATRIO HAFIDZ RAFIE RABBANI",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "101"
}, 
{
  "NAMA": "HARLY PRASETYO",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "102"
}, 
{
  "NAMA": "M. HABIBI DARUSSALAM",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "103"
}, 
{
  "NAMA": "MARLINA AMELIA",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "104"
}, 
{
  "NAMA": "MUHAMMAD ARYO MIDIKA",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "105"
}, 
{
  "NAMA": "NAJWA KHAIRI SILALAHI",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "106"
}, 
{
  "NAMA": "NAURA ZAIFA KHAIRA",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "107"
}, 
{
  "NAMA": "NOOR WAFA AQILA",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "108"
}, 
{
  "NAMA": "SITI AINUN AZZAHRA",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "109"
}, 
{
  "NAMA": "AIRA SA'DANA",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "110"
}, 
{
  "NAMA": "ATHA ZHADA APRILIA",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "080"
}, 
{
  "NAMA": "RAYSA ALYA SHAKILA",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "081"
}, 
{
  "NAMA": "SAFWAN DANISH",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "083"
}, 
{
  "NAMA": "TALITA ANINDYA SYAKIRA",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "084"
}, 
{
  "NAMA": "M. ZAINUL SULTHON",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "085"
}, 
{
  "NAMA": "M.RIZKY RADITYA TOKAN",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "086"
}, 
{
  "NAMA": "MUHAMMAD EMIR AL FURQON",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "087"
}, 
{
  "NAMA": "NUR HUMAIRA AZ ZAHRA",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "088"
}, 
{
  "NAMA": "MUHAMMAD FAIQ JAYYIDAN",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "089"
}, 
{
  "NAMA": "NADIA RIZQI",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "090"
}, 
{
  "NAMA": "QORIN NAESHA SYAWALUNA",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "092"
}, 
{
  "NAMA": "MUHAMMAD FARIZ AL FATIH",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "094"
}, 
{
  "NAMA": "MUHAMMAD RAMA FAKHRULAH",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "096"
}, 
{
  "NAMA": "RADEN FADIL PRATAMA",
  "PEMBIMBING AWAL": "USTADZ HAIDIR",
  "PEMBIMBING BARU": "USTADZ HAIDIR",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "097"
}, 
{
  "NAMA": "ELVIRA AISYAH AZZAHRA",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "125"
}, 
{
  "NAMA": "HAUZAN IRHAF NABIL",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "126"
}, 
{
  "NAMA": "HUMAIRA ASSYIFA NUR JANNAH",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "127"
}, 
{
  "NAMA": "NUR AFIQA HUMAIRA",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "128"
}, 
{
  "NAMA": "FAYRA NUR RABIYA",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "129"
}, 
{
  "NAMA": "ALISIA AURELIA",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "130"
}, 
{
  "NAMA": "AZWA SAFRINA DINIY NAZURAH",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "131"
}, 
{
  "NAMA": "KHADIJAH IZZATI",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "133"
}, 
{
  "NAMA": "M. ADAM AL FARIS",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "134"
}, 
{
  "NAMA": "AINAYYA FATIATUR RAHMA",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "135"
}, 
{
  "NAMA": "ALIKA NAILA PUTRI",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "136"
}, 
{
  "NAMA": "GHINA RAFHANDA",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "137"
}, 
{
  "NAMA": "RISKY ANNISA RASYIDAH",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "254"
}, 
{
  "NAMA": "M. HAFIDZ AR RAYYAN FAHLEVI",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "483"
}, 
{
  "NAMA": "ATIKA MAIRA ZALFA",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN I",
  "NOINFAQ": "111"
}, 
{
  "NAMA": "ALIFA AZKIYA HUSNA",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "132"
}, 
{
  "NAMA": "KHALIZA MOZZAHRA",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "112"
}, 
{
  "NAMA": "AHMAD FAIQ FAHMI",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "113"
}, 
{
  "NAMA": "AISYAH HUMAIRA",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "114"
}, 
{
  "NAMA": "ARIQA SYAHMINA",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "115"
}, 
{
  "NAMA": "AZQIYA TALITA PUTRI",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "116"
}, 
{
  "NAMA": "FARAH KAMILIA YASMIN",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "117"
}, 
{
  "NAMA": "FATIMAH AZKIA",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "118"
}, 
{
  "NAMA": "HERLINA",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "119"
}, 
{
  "NAMA": "KHANSA RAHMINI AZZAHRA",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "120"
}, 
{
  "NAMA": "M. RADITYA RAHMAN",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "121"
}, 
{
  "NAMA": "MUHAMMAD ADLI MAULANA",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "122"
}, 
{
  "NAMA": "QYTARA KHANSA ALHADDA",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "123"
}, 
{
  "NAMA": "SILVIA PUTRI RAMADHANI",
  "PEMBIMBING AWAL": "USTADZAH RISDA",
  "PEMBIMBING BARU": "USTADZAH RISDA",
  "STATUS": "JILID QURAN II",
  "NOINFAQ": "124"
}, 
{
  "NAMA": "AFDALIA",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "054"
}, 
{
  "NAMA": "AHMAD ABIY TSAQIB",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "055"
}, 
{
  "NAMA": "AHMAD FURQON AZZIKRA",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "056"
}, 
{
  "NAMA": "AL FATHIR MUHAMMAD",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "057"
}, 
{
  "NAMA": "ANDI RIKA SANDRA RAHAYU",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "058"
}, 
{
  "NAMA": "AUFA YASMIN AYU ABDIFA",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "059"
}, 
{
  "NAMA": "AUFA ZAHRA AYU ABDITA",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "060"
}, 
{
  "NAMA": "BINTANG NADHIF NAFASAT",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "061"
}, 
{
  "NAMA": "DEALIVINA ADESTI ROHΜΑΝ",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "062"
}, 
{
  "NAMA": "KAYLA ATIIQAH SARI",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "063"
}, 
{
  "NAMA": "LAILY WARITSA",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "064"
}, 
{
  "NAMA": "LAKEISHA 'ARIFAH",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "065"
}, 
{
  "NAMA": "M RAPPA RAMADHAN",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "066"
}, 
{
  "NAMA": "M SAMMAN HAMIZAN",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "067"
}, 
{
  "NAMA": "M.HARIRI",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "068"
}, 
{
  "NAMA": "MAULIA RAHMA WATI",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "069"
}, 
{
  "NAMA": "META RAIHANA",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "070"
}, 
{
  "NAMA": "MIFTAHUR YUMNA MUFAKHAM",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "071"
}, 
{
  "NAMA": "MUHAMMAD ZAINI RAHMAN",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "072"
}, 
{
  "NAMA": "MUHAMMAD ZIYYAN FAIRUZ AL AQTAB",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "073"
}, 
{
  "NAMA": "NAYLA ZHAFIRA FITRIANI",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "074"
}, 
{
  "NAMA": "NOOR IKHSAN SUGI",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "075"
}, 
{
  "NAMA": "RAHMAT HIDAYAT",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "076"
}, 
{
  "NAMA": "RAMSES NAINGGOLAN",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "077"
}, 
{
  "NAMA": "RUBI ALYA MARETA",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "078"
}, 
{
  "NAMA": "SITI HAFIZHAH KHAIRA LUBNA",
  "PEMBIMBING AWAL": "USTADZ SYAMSI",
  "PEMBIMBING BARU": "USTADZ SYAMSI",
  "STATUS": "TAHFIDZ",
  "NOINFAQ": "079"
}, 

//KELAS QURAN





  {
    "NAMA": "AZKA RAYYAN AGFA",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "258"
  },
  {
    "NAMA": "M. ALFALIH",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "FAUZAN",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "M. KHALID AZKA",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "MUHAMMAL NATHAN",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "RAISYA",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "M. RADEYA AL FARAS",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "AISYAH HUMAIRA",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "KIRANA ALIFA HIBATLLAH",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "ALIFA MAULIDA",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "NUR SAFANIYAH",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "M. BILLY FIRDAUS",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "RAQILA NUR FARZAN",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "M.FATIH RISKI B",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "NIZAM SYARIF",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II"
  },
  {
    "NAMA": "M. ZIKRI BAZILA",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II"
  },
  {
    "NAMA": "M. NENO HERDIANA",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II"
  },
  {
    "NAMA": "M. AFKAR PRATAMA",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II"
  },
  {
    "NAMA": "VANNY NOOR AZ ZAHRA",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III"
  },
  {
    "NAMA": "HANIA SYAKIRA",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III"
  },
  {
    "NAMA": "SALSABILA MUHTADIN",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV"
  },
  {
    "NAMA": "PUTRI FENI",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV"
  },
  {
    "NAMA": "SITI ZAFINA WP",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV"
  },
  {
    "NAMA": "ANDI RIZKI DAFA RAMADHAN",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ BAHAUDIN",
    "STATUS": "JILID VI",
    "NOINFAQ": "263"
  },
  {
    "NAMA": "SYAQILA SALSABILA SETIAWAN",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "594"
  },
  {
    "NAMA": "ANDI AISYAH AYUDIA INARA",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "272"
  },
  {
    "NAMA": "ELFAHMI AMMAR MILHAQ",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN"
  },
  {
    "NAMA": "ARIANSYAH",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "470"
  },
  {
    "NAMA": "SITI MAYSAROH",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "339"
  },
  {
    "NAMA": "AKHMAD VIQRI SAPUTRA",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ SOFYAN",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "491"
  },
  {
    "NAMA": "MUHAMMAD TUBAGUS INDRA",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ HUSSAINI",
    "STATUS": "JILID QURAN II",
    "NOINFAQ": "169"
  },
  {
    "NAMA": "MUHAMMAD FARIS RAMADHAN",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "347"
  },
  {
    "NAMA": "MUHAMMAD FAJAR ALFANDI",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "463"
  },
  {
    "NAMA": "GUSTI ALI M AR RAYYAN",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "372"
  },
  {
    "NAMA": "SYAILLA NUR RAMADHANI",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "467"
  },
  {
    "NAMA": "ALLYSA HASYA AFIQAH",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "269"
  },
  {
    "NAMA": "LINGGA DANISH AMINUDIN PURWANTO",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "457"
  },
  {
    "NAMA": "ZAKIA ANIQ MUFLIHAH",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "376"
  },
  {
    "NAMA": "MUHAMMAD LUTFAN ABID",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "293"
  },
  {
    "NAMA": "ACHMAD SIDIQ ASSAMI",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
    "NOINFAQ": "315"
  },
  {
    "NAMA": "ANDRA HARIYADI",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
    "NOINFAQ": "471"
  },
  {
    "NAMA": "MUHAMMAD KHALIQ ALKHALIFY",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "481"
  },
  {
    "NAMA": "ANANDITHA ASSYABIYA ISLAMI",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
    "NOINFAQ": "344"
  },
  {
    "NAMA": "MUHAMMAD LUTH NAUSHADAZKA",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "456"
  },
  {
    "NAMA": "MUHAMMAD AMIN KUTBI",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "377"
  },
  {
    "NAMA": "M. ROYYAN KHIAR ABQORY",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "554"
  },
  {
    "NAMA": "MUHAMMAD ZAUFAN ALL BAKRIE",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "375"
  },
  {
    "NAMA": "M.AZKA APRILIO ADINATA PRASETYA",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "335"
  },
  {
    "NAMA": "DHAFITHA ZAYDA ALWI",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "243"
  },
  {
    "NAMA": "MUHAMMAD ROYYANDI",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "277"
  },
  {
    "NAMA": "SITI ALYA HUMAIRO",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "331"
  },
  {
    "NAMA": "MUHAMMAD AKBAR SAFARUDIN",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "180"
  },
  {
    "NAMA": "GERRAD NAUVALAZKA",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ BAHAUDIN",
    "STATUS": "JILID VI",
    "NOINFAQ": "262"
  },
  {
    "NAMA": "PUTRI NUR ASSIFA",
    "PEMBIMBING AWAL": "USTADZ BAHAUDIN",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
    "NOINFAQ": "203"
  },
  {
    "NAMA": "AMIRA SYIFA AZ ZAHRA",
    "PEMBIMBING AWAL": "USTADZ BAHAUDIN",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
    "NOINFAQ": "490"
  },
  {
    "NAMA": "MUHAMMAD ZIKRIE",
    "PEMBIMBING AWAL": "USTADZ BAHAUDIN",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
        "NOINFAQ": "164"
  },
  {
    "NAMA": "JAUDAH",
    "PEMBIMBING AWAL": "USTADZ BAHAUDIN",
    "PEMBIMBING BARU": "USTADZ BAHAUDIN",
    "STATUS": "JILID VI",
    "NOINFAQ": "341"
  },
  {
    "NAMA": "KHAIRA LUBNA ALTHAFUNNISA",
    "PEMBIMBING AWAL": "USTADZ BAHAUDIN",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "324"
  },
  {
    "NAMA": "MUHAMMAD FIKRI",
    "PEMBIMBING AWAL": "USTADZ BAHAUDIN",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "371"
  },
  {
    "NAMA": "MUHAMMAD DZAKI AFFANDI",
    "PEMBIMBING AWAL": "USTADZ BAHAUDIN",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "171"
  },
  {
    "NAMA": "NADINE MIKAYLA SANDRIA",
    "PEMBIMBING AWAL": "USTADZ BAHAUDIN",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "250"
  },
  {
    "NAMA": "INDRA MAULANA",
    "PEMBIMBING AWAL": "USTADZ BAHAUDIN",
    "PEMBIMBING BARU": "USTADZ BAHAUDIN",
    "STATUS": "JILID VI",
    "NOINFAQ": "330"
  },
  {
    "NAMA": "MUHAMMAD AL FATIH",
    "PEMBIMBING AWAL": "USTADZ BAHAUDIN",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "472"
  },
  {
    "NAMA": "FAIZ HAZMI ANWARI",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "327"
  },
  {
    "NAMA": "AHMAD AZRIL RAZZAN RAHMATULLAH",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "176"
  },
  {
    "NAMA": "AZKIA FILZIA PUTRI",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "239"
  },
  {
    "NAMA": "MAULIDA FEBRIANI PUTRI",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "286"
  },
  {
    "NAMA": "BARKATUL AULYA",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "232"
  },
  {
    "NAMA": "AHMAD GALIH PRIHANDOWO",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
      "NOINFAQ": "280"
  },
  {
    "NAMA": "NUR ATHIFAH",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "247"
  },
  {
    "NAMA": "ALIFA FATHIYYA HAMZAH",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "278"
  },
  {
    "NAMA": "DHAFIN ARYA ROSADI",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "480"
  },
  {
    "NAMA": "NUR 'AINA",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "345"
  },
  {
    "NAMA": "NUR ALIYA TABINA",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "378"
  },
  {
    "NAMA": "MUHAMMAD DAFFA ARYA GHOSSAN",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "322"
  },
  {
    "NAMA": "RAIHAN FERDIAN",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "535"
  },
  {
    "NAMA": "AGHNINA CARIESYA SIBARANI",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "275"
  },
  {
    "NAMA": "RUWAIDA FATIMAH RAHMADANI",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "311"
  },
  {
    "NAMA": "AZIZAH NUR APRILIANI",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
      "NOINFAQ": "455"
  },
  {
    "NAMA": "HIDAYATUL AZKIA",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "534"
  },
  {
    "NAMA": "ZAFRAN YAPIQ",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "314"
  },
  {
    "NAMA": "JIHAN MAULIDA AZKIA",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "369"
  },
  {
    "NAMA": "ZIKRA AMALIA",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ BAHAUDIN",
    "STATUS": "JILID VI",
    "NOINFAQ": "257"
  },
  {
    "NAMA": "KA'AB AHMAD BUSTANI NUR",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "328"
  },
  {
    "NAMA": "DARIN ADELLIA AZ-ZAHRA",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ BAHAUDIN",
    "STATUS": "JILID VI",
    "NOINFAQ": "242"
  },
  {
    "NAMA": "FAQIH GHANI KHAIRI",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "240"
  },
  {
    "NAMA": "GUSTI ALIFIA KIRANA",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "332"
  },
  {
    "NAMA": "M. DAFFA NURRAMDANI",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "154"
  },
  {
    "NAMA": "GHAAZIYA LUBNAYYA",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "248"
  },
  {
    "NAMA": "MUHAMMAD MUHAJIR ANSHORY",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ HUSSAINI",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "336"
  },
  {
    "NAMA": "RAIHAN NURFAIZ",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ HUSSAINI",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "200"
  },
  {
    "NAMA": "M. NOR RAHMAN",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ BAHAUDIN",
    "STATUS": "JILID VI",
    "NOINFAQ": "261"
  },
  {
    "NAMA": "M.HUSEIN ALFANI",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ SOFYAN",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "227"
  },
  {
    "NAMA": "SAID FAUZAN ROSIDI",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ SOFYAN",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "195"
  },
  {
    "NAMA": "SELVIA KHAIRUN ASPIA",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "255"
  },
  {
    "NAMA": "SAN ALI AHMAD",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "492"
  },
  {
    "NAMA": "ALYA IMANI",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "238"
  },
  {
    "NAMA": "MUHAMMAD RASYID FAUZI",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
        "NOINFAQ": "489"
  },
  {
    "NAMA": "NABILA AFIQOH",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "329"
  },
  {
    "NAMA": "ZULFA HUMAIRA",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "317"
  },
  {
    "NAMA": "MUHAMMAD FAHMI RAMADHAN",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "177"
  },
  {
    "NAMA": "MUHAMMAD RAFKA FAIZAR",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "204"
  },
  {
    "NAMA": "⁠FATIH YASIR MUBAROK",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "513"
  },
  {
    "NAMA": "FATIMAH AL KHAIROH",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "474"
  },
  {
    "NAMA": "NUR EFMA WAHIDHA",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "478"
  },
  {
    "NAMA": "FALYA ALIFA INDRAYANA",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "210"
  },
  {
    "NAMA": "KAYLA NURIYA RAHMAN",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI"
  },
  {
    "NAMA": "MUHAMMAD AFDILLAH",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "172"
  },
  {
    "NAMA": "AISYAH AFIFA A.",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI"
  },
  {
    "NAMA": "INDRA LESMANA",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "287"
  },
  {
    "NAMA": "SIRHAN FIKRI ROSIDI",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "256"
  },
  {
    "NAMA": "MUHAMMAD ROHIID AL ANIS",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "296"
  },
  {
    "NAMA": "MUHAMMAD ABIZHAR",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "459"
  },
  {
    "NAMA": "IQBAL MURISKI",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "351"
  },
  {
    "NAMA": "KAYLA ATIIQAH SARI",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "063"
  },
  {
    "NAMA": "MUHAMMAD HUD AR RAYYAN",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "367"
  },
  {
    "NAMA": "KAYLA AZZAHRA RIFA'I ",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "548"
  },
  {
    "NAMA": "⁠AISYAH RAIHANAH",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
        "NOINFAQ": "279"
  },
  {
    "NAMA": "M. ZAINI ALFAT",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "550"
  },
  {
    "NAMA": "KHALISA PUTRI",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "325"
  },
  {
    "NAMA": "WIRDA HALIMATUS SA'DIAH",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "366"
  },
  {
    "NAMA": "M. IQRAM SYARIF",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "549"
  },
  {
    "NAMA": "SYAFIRA ALFATHUNNISA",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "374"
  },
  {
    "NAMA": "ALTHAF BASYA MISYARAJA",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "267"
  },
  {
    "NAMA": "MUHAMMAD IRSYAN GAZALI",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "212"
  },
  {
    "NAMA": "NADHIFA AYU FAIQAH",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "299"
  },
  {
    "NAMA": "NADA NURANI ALIANSYAH",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "509"
  },
  {
    "NAMA": "AISYAH AQILAH",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
    "NOINFAQ": "271"
  },
  {
    "NAMA": "ALIFA AZ-ZAHRA",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
    "NOINFAQ": "350"
  },
  {
    "NAMA": "AHMAD NAZAMUDDIN",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "276"
  },
  {
    "NAMA": "ALESHA KAYLA NADHIFA",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
    "NOINFAQ": "326"
  },
  {
    "NAMA": "AHMAD ZAIEN WAFA",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "266"
  },
  {
    "NAMA": "AYSHA RAMADANI",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "174"
  },
  {
    "NAMA": "MUHAMMAD RAIHAN HAFIZH",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "165"
  },
  {
    "NAMA": "ALFARIZKY MELAN PRATAMA",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "281"
  },
  {
    "NAMA": "ZAINAL ILMI",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "334"
  },
  {
    "NAMA": "MUHAMMAD HAIKAL BAGUS",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "382"
  },
  {
    "NAMA": "FAJRIANSYAH",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "233"
  },
  {
    "NAMA": "WIRDA NUR HASANAH",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "NUR AISYAH HUMAIRA",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I",
    "NOINFAQ": "576"
  },
  {
    "NAMA": "M. MAHASIN NOVAL",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "574"
  },
  {
    "NAMA": "AHMAD SYAUQI HABIBI",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "580"
  },
  {
    "NAMA": "MUHAMMAD MIRZA ALIANDRA",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "589"
  },
  {
    "NAMA": "M. KAHFI ARRAHMAN",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "588"
  },
  {
    "NAMA": "MAULANA MALIK IBRAHIM",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "573"
  },
  {
    "NAMA": "MUHAMMAD ADELLIO BRAMASTA",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "517"
  },
  {
    "NAMA": "FAQIH NAZRIL KHALIF",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "584"
  },
  {
    "NAMA": "ABDU RAHDIKA NAHRY",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "571"
  },
  {
    "NAMA": "AHMAD AL-FATIH NUR ADABY",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "516"
  },
  {
    "NAMA": "M. UMAR ZAFLAN ALTTUDA",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
      "NOINFAQ": "575"
  },
  {
    "NAMA": "SYAHILA AZMI",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "578"
  },
  {
    "NAMA": "NUR RAZIBUIA HANDAYANI",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "577"
  },
  {
    "NAMA": "M. RASYID RAIHAN",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "590"
  },
  {
    "NAMA": "KHAIRUL SAPUTRA",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "572"
  },
  {
    "NAMA": "M. SULTHAN MALIK",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
    "NOINFAQ": "591"
  },
  {
    "NAMA": "ARUNA GHAISAN A. F",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
    "NOINFAQ": "583"
  },
  {
    "NAMA": "GT. DAFA",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "585"
  },
  {
    "NAMA": "QONITA HANIFA ALMAHIRA",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "593"
  },
  {
    "NAMA": "ALSYAH NUR ALMIRA",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "582"
  },
  {
    "NAMA": "M. ZAYD RYS ALGHIFARI",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID III",
    "NOINFAQ": "592"
  },
  {
    "NAMA": "ALIFAH RAHMANTI PUTRI",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID III",
    "NOINFAQ": "581"
  },
  {
    "NAMA": "MUH. AL FATIH",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID III",
    "NOINFAQ": "587"
  },
  {
    "NAMA": "IZZFAHIM ANAQI",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID III",
    "NOINFAQ": "586"
  },
  {
    "NAMA": "GUSTI KHALID RAHMAN SADI'",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "570"
  },
  {
    "NAMA": "KUMALA AFIFA NAHDA RAFANDA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "352"
  },
  {
    "NAMA": "NUR AULIA SAFITRI",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "505"
  },
  {
    "NAMA": "RIZKY NUR AQILLA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "309"
  },
  {
    "NAMA": "AYSHA NABILA PRANTAU",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "357"
  },
  {
    "NAMA": "NAYSILLA NUR MAYDINI",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "501"
  },
  {
    "NAMA": "ALMIRA ZHAFIRA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "531"
  },
  {
    "NAMA": "KHUMAIRA PUTRI ASY'ARI      ",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "519"
  },
  {
    "NAMA": "ALISHA NAILA MIZA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "362"
  },
  {
    "NAMA": "M. HAFIZH FATURRAHMAN",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "360"
  },
  {
    "NAMA": "RAYA NOVITA SARI",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "358"
  },
  {
    "NAMA": "AKIFAH NAYLA NURHIJRAH",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "362"
  },
  {
    "NAMA": "MUHAMMAD RAYHAN",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
    "NOINFAQ": "295"
  },
  {
    "NAMA": "SARAH AZMIRA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
    "NOINFAQ": "312"
  },
  {
    "NAMA": "MUHAMMAD AZKA RANENDRA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
    "NOINFAQ": "503"
  },
  {
    "NAMA": "FATIA AULIA ANNISA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
    "NOINFAQ": "363"
  },
  {
    "NAMA": "NATANIA AISYAH NUHA ZAHIRA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "300"
  },
  {
    "NAMA": "AMALIA PUTRI",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "355"
  },
  {
    "NAMA": "SITI FADILLAH",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "504"
  },
  {
    "NAMA": "FAUZA NUR RIZKY",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID III",
    "NOINFAQ": "356"
  },
  {
    "NAMA": "BILQIS KHAIRUNNISA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
        "NOINFAQ": "486"
  },
  {
    "NAMA": "MUHAMMAD NAUFAL FAEYZA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
    "NOINFAQ": "454"
  },
  {
    "NAMA": "MUHAMMAD ALZHAFRAN FARDILA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "565"
  },
  {
    "NAMA": "MUHAMMAD ALFAT KHAIRY",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "495"
  },
  {
    "NAMA": "ABDILLAH ALGHIFARI IBERAHIM",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "349"
  },
  {
    "NAMA": "M. AQSAN MUSYAFA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "496"
  },
  {
    "NAMA": "MUTIA NUR AZZAHRA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "298"
  },
  {
    "NAMA": "MUHAMMAD AZHAR ALRISAM",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "359"
  },
  {
    "NAMA": "MUHAMMAD AIDIL SYAFE'I",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "552"
  },
  {
    "NAMA": "RAESHA YUMNA ADZKIA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "303"
  },
  {
    "NAMA": "MUHAMMAD ZAKY RAMADHAN",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "498"
  },
  {
    "NAMA": "FATHIN AULIA",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "564"
  },
  {
    "NAMA": "MUHAMMAD LUTFI SAPUTRA",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "521"
  },
  {
    "NAMA": "ALIFIA NAVISHA",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "559"
  },
  {
    "NAMA": "SYARIFAH SHIDQIA",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "560"
  },
  {
    "NAMA": "M. ARKHAN R.",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "ALI RAYYAN RIZKY",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "539"
  },
  {
    "NAMA": "AFFABIAN MUSYAFA AHMAD",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "563"
  },
  {
    "NAMA": "AFIQAH NAILA",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "M. ARFAN",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "568"
  },
  {
    "NAMA": "M. RIFDHIL ARHAMY",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "561"
  },
  {
    "NAMA": "NUR MIFTAHUL JANNAH",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "566"
  },
  {
    "NAMA": "M. MAHDI YUSUF",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "562"
  },
  {
    "NAMA": "M. ABYAN ARJUNA PASURA ",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
        "NOINFAQ": "523"
  },
  {
    "NAMA": "ABDULLAH ARAFAT ATTA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "551"
  },
  {
    "NAMA": "RISKA NUR BAINAH",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "537"
  },
  {
    "NAMA": "MUHAMMAD ALFARIZQI  ",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "541"
  },
  {
    "NAMA": "⁠ARKAAN HARITH HAFI",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
        "NOINFAQ": "538"
  },
  {
    "NAMA": "ZAINA ALIFAH",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
         "NOINFAQ": "540"
  },
  {
    "NAMA": "MUHAMMAD ALTHAF HAFIZY",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "520"
  },
  {
    "NAMA": "FAHRIL RIZKY PRATAMA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "545"
  },
  {
    "NAMA": "REYNA AURELIA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "543"
  },
  {
    "NAMA": "MUHAMMAD ADEB AL GAZALI",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "546"
  },
  {
    "NAMA": "NAFISA SHARIN NASYWA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "542"
  },
  {
    "NAMA": "HAFIZAH NUR AULIA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "547"
  },
  {
    "NAMA": "MUHAMMAD ARKHA AL FAIRUZ",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "518"
  },
  {
    "NAMA": "MUHAMMAD ARIF FADIL",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "544"
  },
  {
    "NAMA": "⁠MUHAMMAD TSAQIB HERSYA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
        "NOINFAQ": "297"
  },
  {
    "NAMA": "TRIYANA SAFITRI",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
            "NOINFAQ": "313"
  },
  {
    "NAMA": "RINDANG RIZKI ANANDA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
    "NOINFAQ": "361"
  },
  {
    "NAMA": "M. ALI ZABER",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
    "NOINFAQ": "290"
  },
  {
    "NAMA": "⁠RENDRA MAHARDIKA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
        "NOINFAQ": "307"
  },
  {
    "NAMA": "NAYRA RAISA DINAR",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
          "NOINFAQ": "302"
  },
  {
    "NAMA": "AYANA MUKHBITA MARYAM",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "342"
  },
  {
    "NAMA": "RAYYA STARLA ADZKADINA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "511"
  },
  {
    "NAMA": "MUHAMMAD SAKHA AT THAHIR RAMADHAN",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "464"
  },
  {
    "NAMA": "HAVA HARAIDAN SAFIRA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "370"
  },
  {
    "NAMA": "AHMAD ZAINI DAHLAN",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "365"
  },
  {
    "NAMA": "RUSNI ADAM",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "310"
  },
  {
    "NAMA": "RAIHANA AINUN MARDIAH",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "306"
  },
  {
    "NAMA": "M. HAUFAN HAZZA ABQORY",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "536"

  },
  {
    "NAMA": "M. AZKA PUTRA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "462"
  },
  {
    "NAMA": "FEBRIYANI",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "353"
  },
  {
    "NAMA": "M. ALMAN. B",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "354"
  },
  {
    "NAMA": "MUHAMMAD ARSHAD AL FATIH ASTADIWANGSA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "292"
  },
  {
    "NAMA": "RAFFA MULYATAMA SARAGIH",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "304"
  },
  {
    "NAMA": "ANDI ARSYILA HUMAIRA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "524"
  },
  {
    "NAMA": "ALMAIRA NURFAUZIAH",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "512"
  },
  {
    "NAMA": "RULITA AZZAHRA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "506"
  },
  {
    "NAMA": "RAISYA NUR AQIFA NAYLA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "514"
  },
  {
    "NAMA": "NAILA AZKADINA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "522"
  },
  {
    "NAMA": "NUR AMELIA NAZIHA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "499"
  },
  {
    "NAMA": "FARYZA ANNISA FITRIA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
        "NOINFAQ": "525"
  },
  {
    "NAMA": "AHMAD RAFFASYA ALFARIZI",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID III",
    "NOINFAQ": "500"
  },
  {
    "NAMA": "NUR AFIFAH",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID III"
  },
  {
    "NAMA": "M. FADILLAH RAMLAN",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID III",
    "NOINFAQ": "364"
  },
  {
    "NAMA": "MUHAMMAD YUSUF",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID III",
    "NOINFAQ": "497"
  },
  {
    "NAMA": "KIOSI ALTAF",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "273"
  },
  {
    "NAMA": "ZHAFIRA RASYIFA SALWA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "211"
  },
  {
    "NAMA": "SASKIA ANASTASYA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "477"
  },
  {
    "NAMA": "MUHAMMAD ZAIDAN RAHMAN",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "167"
  },
  {
    "NAMA": "PUTRI NABILA AZZAHRA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
    "NOINFAQ": "206"
  },
  {
    "NAMA": "FAUZIAH",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "209"
  },
  {
    "NAMA": "SITI AISYAH",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "170"
  },
  {
    "NAMA": "MUHAMMAD YUSUF RACHMAN",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "205"
  },
  {
    "NAMA": "HAFIDZAH AZZAHRA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "179"
  },
  {
    "NAMA": "AHMAD AL FARIZQI",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "265"
  },
  {
    "NAMA": "NAZIA ARSYIFA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "333"
  },
  {
    "NAMA": "ELSA RAIDA RAHMAWATI",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "244"
  },
  {
    "NAMA": "KEYRA ANDITA BALQIS",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "323"
  },
  {
    "NAMA": "ARSY PUTRA FIRMANSYAH",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "231"
  },
  {
    "NAMA": "NADHIRA IMADINA ADIBA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "379"
  },
  {
    "NAMA": "AISHA ARSYIFA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "268"
  },
  {
    "NAMA": "MUHAMMAD AL FATIH RAMADHAN",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "569"
  },
  {
    "NAMA": "ADELIA ZAHRATUSSHOFA",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "288"
  },
  {
    "NAMA": "M. REZA EFANSYAH",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "348"
  },
  {
    "NAMA": "MUHAMMAD HABIBIE",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "207"
  },
  {
    "NAMA": "ANISA AZAHRA",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "285"
  },
  {
    "NAMA": "ALMEERA NURUL RASYADA",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "282"
  },
  {
    "NAMA": "AHMAD KEMAL REIS LIZUIRABIH",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
    "NOINFAQ": "510"
  },
  {
    "NAMA": "M.AZKA RIDLONI                ",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
        "NOINFAQ": "461"
  },
  {
    "NAMA": "AKHMAD HABIBIE",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "468"
  },
  {
    "NAMA": "MUHAMMAD NABIL ASY ARI",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "494"
  },
  {
    "NAMA": "HAFI AHMAD SUBAKTI",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
        "NOINFAQ": "469"
  }





]

//hamburger menu
// Fungsi untuk mengubah tampilan menu pada perangkat mobile
document.getElementById('menu-toggle').onclick = function() {
    const mobileMenu = document.getElementById('mobile-menu');
    mobileMenu.classList.toggle('hidden'); // Menyembunyikan atau menampilkan menu
}
