// script.js

// Data yang diberikan dalam format JSON
const data = [
  {
    "NAMA": "AZKA RAYYAN AGFA",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "258"
  },
  {
    "NAMA": "M. ALFALIH",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "FAUZAN",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "M. KHALID AZKA",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "MUHAMMAL NATHAN",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "RAISYA",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "M. RADEYA AL FARAS",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "AISYAH HUMAIRA",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "KIRANA ALIFA HIBATLLAH",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "ALIFA MAULIDA",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "NUR SAFANIYAH",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "M. BILLY FIRDAUS",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "RAQILA NUR FARZAN",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "M.FATIH RISKI B",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "NIZAM SYARIF",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II"
  },
  {
    "NAMA": "M. ZIKRI BAZILA",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II"
  },
  {
    "NAMA": "M. NENO HERDIANA",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II"
  },
  {
    "NAMA": "M. AFKAR PRATAMA",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II"
  },
  {
    "NAMA": "RANNY",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III"
  },
  {
    "NAMA": "HANIA SYAKIRA",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III"
  },
  {
    "NAMA": "SALSABILA MUHTADIN",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV"
  },
  {
    "NAMA": "PUTRI FENI",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV"
  },
  {
    "NAMA": "SITI ZAFINA WP",
    "PEMBIMBING AWAL": "SANTRI BARU",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV"
  },
  {
    "NAMA": "ANDI RIZKI DAFA RAMADHAN",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ BAHAUDIN",
    "STATUS": "JILID VI",
    "NOINFAQ": "263"
  },
  {
    "NAMA": "SYAQILA SALSABILA SETIAWAN",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "594"
  },
  {
    "NAMA": "ANDI AISYAH AYUDIA INARA",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "272"
  },
  {
    "NAMA": "ELFAHMI AMMAR MILHAQ",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN"
  },
  {
    "NAMA": "ARIANSYAH",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "470"
  },
  {
    "NAMA": "SITI MAYSAROH",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "339"
  },
  {
    "NAMA": "AKHMAD VIQRI SAPUTRA",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ SOFYAN",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "491"
  },
  {
    "NAMA": "MUHAMMAD TUBAGUS INDRA",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ HAIDIR",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "169"
  },
  {
    "NAMA": "MUHAMMAD FARIS RAMADHAN",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "347"
  },
  {
    "NAMA": "MUHAMMAD FAJAR ALFANDI",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "463"
  },
  {
    "NAMA": "GUSTI ALI M AR RAYYAN",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "372"
  },
  {
    "NAMA": "SYAILLA NUR RAMADHANI",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "467"
  },
  {
    "NAMA": "ALLYSA HASYA AFIQAH",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "269"
  },
  {
    "NAMA": "LINGGA DANISH AMINUDIN PURWANTO",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "457"
  },
  {
    "NAMA": "ZAKIA ANIQ MUFLIHAH",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "376"
  },
  {
    "NAMA": "MUHAMMAD LUTFAN ABID",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "293"
  },
  {
    "NAMA": "ACHMAD SIDIQ ASSAMI",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
    "NOINFAQ": "315"
  },
  {
    "NAMA": "ANDRA HARIYADI",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
    "NOINFAQ": "471"
  },
  {
    "NAMA": "MUHAMMAD KHALIQ ALKHALIFY",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "481"
  },
  {
    "NAMA": "ANANDITHA ASSYABIYA ISLAMI",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
    "NOINFAQ": "344"
  },
  {
    "NAMA": "MUHAMMAD LUTH NAUSHADAZKA",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "456"
  },
  {
    "NAMA": "MUHAMMAD AMIN KUTBI",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "377"
  },
  {
    "NAMA": "M. ROYYAN KHIAR ABQORY",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "554"
  },
  {
    "NAMA": "MUHAMMAD ZAUFAN ALL BAKRIE",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "375"
  },
  {
    "NAMA": "M.AZKA APRILIO ADINATA PRASETYA",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "335"
  },
  {
    "NAMA": "DHAFITHA ZAYDA ALWI",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "243"
  },
  {
    "NAMA": "MUHAMMAD ROYYANDI",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "277"
  },
  {
    "NAMA": "SITI ALYA HUMAIRO",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "331"
  },
  {
    "NAMA": "MUHAMMAD AKBAR SAFARUDIN",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "180"
  },
  {
    "NAMA": "GERRAD NAUVALAZKA",
    "PEMBIMBING AWAL": "JUNI WARDANI",
    "PEMBIMBING BARU": "USTADZ BAHAUDIN",
    "STATUS": "JILID VI",
    "NOINFAQ": "262"
  },
  {
    "NAMA": "PUTRI NUR ASSIFA",
    "PEMBIMBING AWAL": "USTADZ BAHAUDIN",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
    "NOINFAQ": "203"
  },
  {
    "NAMA": "AMIRA SYIFA AZ ZAHRA",
    "PEMBIMBING AWAL": "USTADZ BAHAUDIN",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
    "NOINFAQ": "490"
  },
  {
    "NAMA": "MUHAMMAD ZIKRIE",
    "PEMBIMBING AWAL": "USTADZ BAHAUDIN",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
        "NOINFAQ": "164"
  },
  {
    "NAMA": "JAUDAH",
    "PEMBIMBING AWAL": "USTADZ BAHAUDIN",
    "PEMBIMBING BARU": "USTADZ BAHAUDIN",
    "STATUS": "JILID VI",
    "NOINFAQ": "341"
  },
  {
    "NAMA": "KHAIRA LUBNA ALTHAFUNNISA",
    "PEMBIMBING AWAL": "USTADZ BAHAUDIN",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "324"
  },
  {
    "NAMA": "MUHAMMAD FIKRI",
    "PEMBIMBING AWAL": "USTADZ BAHAUDIN",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "371"
  },
  {
    "NAMA": "MUHAMMAD DZAKI AFFANDI",
    "PEMBIMBING AWAL": "USTADZ BAHAUDIN",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "171"
  },
  {
    "NAMA": "NADINE MIKAYLA SANDRIA",
    "PEMBIMBING AWAL": "USTADZ BAHAUDIN",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "250"
  },
  {
    "NAMA": "INDRA MAULANA",
    "PEMBIMBING AWAL": "USTADZ BAHAUDIN",
    "PEMBIMBING BARU": "USTADZ BAHAUDIN",
    "STATUS": "JILID VI",
    "NOINFAQ": "330"
  },
  {
    "NAMA": "MUHAMMAD AL FATIH",
    "PEMBIMBING AWAL": "USTADZ BAHAUDIN",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "472"
  },
  {
    "NAMA": "FAIZ HAZMI ANWARI",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "327"
  },
  {
    "NAMA": "AHMAD AZRIL RAZZAN RAHMATULLAH",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "176"
  },
  {
    "NAMA": "AZKIA FILZIA PUTRI",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "239"
  },
  {
    "NAMA": "MAULIDA FEBRIANI PUTRI",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "286"
  },
  {
    "NAMA": "BARKATUL AULYA",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "232"
  },
  {
    "NAMA": "AHMAD GALIH PRIHANDOWO",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
      "NOINFAQ": "280"
  },
  {
    "NAMA": "NUR ATHIFAH",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "247"
  },
  {
    "NAMA": "ALIFA FATHIYYA HAMZAH",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "278"
  },
  {
    "NAMA": "DHAFIN ARYA ROSADI",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "480"
  },
  {
    "NAMA": "NUR 'AINA",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "345"
  },
  {
    "NAMA": "NUR ALIYA TABINA",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "378"
  },
  {
    "NAMA": "MUHAMMAD DAFFA ARYA GHOSSAN",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "322"
  },
  {
    "NAMA": "RAIHAN FERDIAN",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "535"
  },
  {
    "NAMA": "AGHNINA CARIESYA SIBARANI",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "275"
  },
  {
    "NAMA": "RUWAIDA FATIMAH RAHMADANI",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "311"
  },
  {
    "NAMA": "AZIZAH NUR APRILIANI",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
      "NOINFAQ": "455"
  },
  {
    "NAMA": "HIDAYATUL AZKIA",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "534"
  },
  {
    "NAMA": "ZAFRAN YAPIQ",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "314"
  },
  {
    "NAMA": "JIHAN MAULIDA AZKIA",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "369"
  },
  {
    "NAMA": "ZIKRA AMALIA",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ BAHAUDIN",
    "STATUS": "JILID VI",
    "NOINFAQ": "257"
  },
  {
    "NAMA": "KA'AB AHMAD BUSTANI NUR",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "328"
  },
  {
    "NAMA": "DARIN ADELLIA AZ-ZAHRA",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZ BAHAUDIN",
    "STATUS": "JILID VI",
    "NOINFAQ": "242"
  },
  {
    "NAMA": "FAQIH GHANI KHAIRI",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "240"
  },
  {
    "NAMA": "GUSTI ALIFIA KIRANA",
    "PEMBIMBING AWAL": "USTADZ SYARIF",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "332"
  },
  {
    "NAMA": "M. DAFFA NURRAMDANI",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "154"
  },
  {
    "NAMA": "GHAAZIYA LUBNAYYA",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "248"
  },
  {
    "NAMA": "MUHAMMAD MUHAJIR ANSHORY",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ HUSSAINI",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "336"
  },
  {
    "NAMA": "RAIHAN NURFAIZ",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ HUSSAINI",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "200"
  },
  {
    "NAMA": "M. NOR RAHMAN",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ BAHAUDIN",
    "STATUS": "JILID VI",
    "NOINFAQ": "261"
  },
  {
    "NAMA": "M.HUSEIN ALFANI",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ SOFYAN",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "227"
  },
  {
    "NAMA": "SAID FAUZAN ROSIDI",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ SOFYAN",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "195"
  },
  {
    "NAMA": "SELVIA KHAIRUN ASPIA",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID QURAN",
    "NOINFAQ": "255"
  },
  {
    "NAMA": "SAN ALI AHMAD",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "492"
  },
  {
    "NAMA": "ALYA IMANI",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "238"
  },
  {
    "NAMA": "MUHAMMAD RASYID FAUZI",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
        "NOINFAQ": "489"
  },
  {
    "NAMA": "NABILA AFIQOH",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "329"
  },
  {
    "NAMA": "ZULFA HUMAIRA",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "317"
  },
  {
    "NAMA": "MUHAMMAD FAHMI RAMADHAN",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "177"
  },
  {
    "NAMA": "MUHAMMAD RAFKA FAIZAR",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "204"
  },
  {
    "NAMA": "⁠FATIH YASIR MUBAROK",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "513"
  },
  {
    "NAMA": "FATIMAH AL KHAIROH",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "474"
  },
  {
    "NAMA": "NUR EFMA WAHIDHA",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "478"
  },
  {
    "NAMA": "FALYA ALIFA INDRAYANA",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "210"
  },
  {
    "NAMA": "KAYLA NURIYA RAHMAN",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI"
  },
  {
    "NAMA": "MUHAMMAD AFDILLAH",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "172"
  },
  {
    "NAMA": "AISYAH AFIFA A.",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI"
  },
  {
    "NAMA": "INDRA LESMANA",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "287"
  },
  {
    "NAMA": "SIRHAN FIKRI ROSIDI",
    "PEMBIMBING AWAL": "USTADZ TAHMID",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "256"
  },
  {
    "NAMA": "MUHAMMAD ROHIID AL ANIS",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "296"
  },
  {
    "NAMA": "MUHAMMAD ABIZHAR",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "459"
  },
  {
    "NAMA": "IQBAL MURISKI",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "351"
  },
  {
    "NAMA": "KAYLA ATIIQAH SARI",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "063"
  },
  {
    "NAMA": "MUHAMMAD HUD AR RAYYAN",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "367"
  },
  {
    "NAMA": "KAYLA AZZAHRA RIFA'I ",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "548"
  },
  {
    "NAMA": "⁠AISYAH RAIHANAH",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
        "NOINFAQ": "279"
  },
  {
    "NAMA": "M. ZAINI ALFAT",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "550"
  },
  {
    "NAMA": "KHALISA PUTRI",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "325"
  },
  {
    "NAMA": "WIRDA HALIMATUS SA'DIAH",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "366"
  },
  {
    "NAMA": "M. IQRAM SYARIF",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "549"
  },
  {
    "NAMA": "SYAFIRA ALFATHUNNISA",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "374"
  },
  {
    "NAMA": "ALTHAF BASYA MISYARAJA",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "267"
  },
  {
    "NAMA": "MUHAMMAD IRSYAN GAZALI",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "212"
  },
  {
    "NAMA": "NADHIFA AYU FAIQAH",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "299"
  },
  {
    "NAMA": "NADA NURANI ALIANSYAH",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "509"
  },
  {
    "NAMA": "AISYAH AQILAH",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
    "NOINFAQ": "271"
  },
  {
    "NAMA": "ALIFA AZ-ZAHRA",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
    "NOINFAQ": "350"
  },
  {
    "NAMA": "AHMAD NAZAMUDDIN",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "276"
  },
  {
    "NAMA": "ALESHA KAYLA NADHIFA",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
    "NOINFAQ": "326"
  },
  {
    "NAMA": "AHMAD ZAIEN WAFA",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "266"
  },
  {
    "NAMA": "AYSHA RAMADANI",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "174"
  },
  {
    "NAMA": "MUHAMMAD RAIHAN HAFIZH",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "165"
  },
  {
    "NAMA": "ALFARIZKY MELAN PRATAMA",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "281"
  },
  {
    "NAMA": "ZAINAL ILMI",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "334"
  },
  {
    "NAMA": "MUHAMMAD HAIKAL BAGUS",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "382"
  },
  {
    "NAMA": "FAJRIANSYAH",
    "PEMBIMBING AWAL": "USTADZAH SANAH",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "233"
  },
  {
    "NAMA": "WIRDA NUR HASANAH",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "NUR AISYAH HUMAIRA",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID I",
    "NOINFAQ": "576"
  },
  {
    "NAMA": "M. MAHASIN NOVAL",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "574"
  },
  {
    "NAMA": "AHMAD SYAUQI HABIBI",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "580"
  },
  {
    "NAMA": "MUHAMMAD MIRZA ALIANDRA",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "589"
  },
  {
    "NAMA": "M. KAHFI ARRAHMAN",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "588"
  },
  {
    "NAMA": "MAULANA MALIK IBRAHIM",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "573"
  },
  {
    "NAMA": "MUHAMMAD ADELLIO BRAMASTA",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "517"
  },
  {
    "NAMA": "FAQIH NAZRIL KHALIF",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "584"
  },
  {
    "NAMA": "ABDU RAHDIKA NAHRY",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "571"
  },
  {
    "NAMA": "AHMAD AL-FATIH NUR ADABY",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "516"
  },
  {
    "NAMA": "M. UMAR ZAFLAN ALTTUDA",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
      "NOINFAQ": "575"
  },
  {
    "NAMA": "SYAHILA AZMI",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "578"
  },
  {
    "NAMA": "NUR RAZIBUIA HANDAYANI",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "577"
  },
  {
    "NAMA": "M. RASYID RAIHAN",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "590"
  },
  {
    "NAMA": "KHAIRUL SAPUTRA",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "572"
  },
  {
    "NAMA": "M. SULTHAN MALIK",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
    "NOINFAQ": "591"
  },
  {
    "NAMA": "ARUNA GHAISAN A. F",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
    "NOINFAQ": "583"
  },
  {
    "NAMA": "GT. DAFA",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "585"
  },
  {
    "NAMA": "QONITA HANIFA ALMAHIRA",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "593"
  },
  {
    "NAMA": "ALSYAH NUR ALMIRA",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "582"
  },
  {
    "NAMA": "M. ZAYD RYS ALGHIFARI",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID III",
    "NOINFAQ": "592"
  },
  {
    "NAMA": "ALIFAH RAHMANTI PUTRI",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID III",
    "NOINFAQ": "581"
  },
  {
    "NAMA": "MUH. AL FATIH",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID III",
    "NOINFAQ": "587"
  },
  {
    "NAMA": "IZZFAHIM ANAQI",
    "PEMBIMBING AWAL": "USTADZAH ASTRID",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID III",
    "NOINFAQ": "586"
  },
  {
    "NAMA": "GUSTI KHALID RAHMAN SADI'",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "570"
  },
  {
    "NAMA": "KUMALA AFIFA NAHDA RAFANDA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "352"
  },
  {
    "NAMA": "NUR AULIA SAFITRI",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "505"
  },
  {
    "NAMA": "RIZKY NUR AQILLA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "309"
  },
  {
    "NAMA": "AYSHA NABILA PRANTAU",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "357"
  },
  {
    "NAMA": "NAYSILLA NUR MAYDINI",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "501"
  },
  {
    "NAMA": "ALMIRA ZHAFIRA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "531"
  },
  {
    "NAMA": "KHUMAIRA PUTRI ASY'ARI      ",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "519"
  },
  {
    "NAMA": "ALISHA NAILA MIZA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "362"
  },
  {
    "NAMA": "M. HAFIZH FATURRAHMAN",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "360"
  },
  {
    "NAMA": "RAYA NOVITA SARI",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "358"
  },
  {
    "NAMA": "AKIFAH NAYLA NURHIJRAH",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "362"
  },
  {
    "NAMA": "MUHAMMAD RAYHAN",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
    "NOINFAQ": "295"
  },
  {
    "NAMA": "SARAH AZMIRA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
    "NOINFAQ": "312"
  },
  {
    "NAMA": "MUHAMMAD AZKA RANENDRA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
    "NOINFAQ": "503"
  },
  {
    "NAMA": "FATIA AULIA ANNISA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
    "NOINFAQ": "363"
  },
  {
    "NAMA": "NATANIA AISYAH NUHA ZAHIRA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "300"
  },
  {
    "NAMA": "AMALIA PUTRI",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "355"
  },
  {
    "NAMA": "SITI FADILLAH",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "504"
  },
  {
    "NAMA": "FAUZA NUR RIZKY",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID III",
    "NOINFAQ": "356"
  },
  {
    "NAMA": "BILQIS KHAIRUNNISA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
        "NOINFAQ": "486"
  },
  {
    "NAMA": "MUHAMMAD NAUFAL FAEYZA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
    "NOINFAQ": "454"
  },
  {
    "NAMA": "MUHAMMAD ALZHAFRAN FARDILA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "565"
  },
  {
    "NAMA": "MUHAMMAD ALFAT KHAIRY",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "495"
  },
  {
    "NAMA": "ABDILLAH ALGHIFARI IBERAHIM",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "349"
  },
  {
    "NAMA": "M. AQSAN MUSYAFA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "496"
  },
  {
    "NAMA": "MUTIA NUR AZZAHRA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "298"
  },
  {
    "NAMA": "MUHAMMAD AZHAR ALRISAM",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "359"
  },
  {
    "NAMA": "MUHAMMAD AIDIL SYAFE'I",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "552"
  },
  {
    "NAMA": "RAESHA YUMNA ADZKIA",
    "PEMBIMBING AWAL": "USTADZAH DIAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "303"
  },
  {
    "NAMA": "MUHAMMAD ZAKY RAMADHAN",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "498"
  },
  {
    "NAMA": "FATHIN AULIA",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "564"
  },
  {
    "NAMA": "MUHAMMAD LUTFI SAPUTRA",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "521"
  },
  {
    "NAMA": "ALIFIA NAVISHA",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "559"
  },
  {
    "NAMA": "SYARIFAH SHIDQIA",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "560"
  },
  {
    "NAMA": "M. ARKHAN R.",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "ALI RAYYAN RIZKY",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "539"
  },
  {
    "NAMA": "AFFABIAN MUSYAFA AHMAD",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "563"
  },
  {
    "NAMA": "AFIQAH NAILA",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I"
  },
  {
    "NAMA": "M. ARFAN",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "568"
  },
  {
    "NAMA": "M. RIFDHIL ARHAMY",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "561"
  },
  {
    "NAMA": "NUR MIFTAHUL JANNAH",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "566"
  },
  {
    "NAMA": "M. MAHDI YUSUF",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "562"
  },
  {
    "NAMA": "M. ABYAN ARJUNA PASURA ",
    "PEMBIMBING AWAL": "USTADZAH DINDA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
        "NOINFAQ": "523"
  },
  {
    "NAMA": "ABDULLAH ARAFAT ATTA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "551"
  },
  {
    "NAMA": "RISKA NUR BAINAH",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "537"
  },
  {
    "NAMA": "MUHAMMAD ALFARIZQI  ",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
    "NOINFAQ": "541"
  },
  {
    "NAMA": "⁠ARKAAN HARITH HAFI",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
        "NOINFAQ": "538"
  },
  {
    "NAMA": "ZAINA ALIFAH",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID I",
         "NOINFAQ": "540"
  },
  {
    "NAMA": "MUHAMMAD ALTHAF HAFIZY",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "520"
  },
  {
    "NAMA": "FAHRIL RIZKY PRATAMA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "545"
  },
  {
    "NAMA": "REYNA AURELIA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "543"
  },
  {
    "NAMA": "MUHAMMAD ADEB AL GAZALI",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "546"
  },
  {
    "NAMA": "NAFISA SHARIN NASYWA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "542"
  },
  {
    "NAMA": "HAFIZAH NUR AULIA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II"
  },
  {
    "NAMA": "MUHAMMAD ARKHA AL FAIRUZ",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "518"
  },
  {
    "NAMA": "MUHAMMAD ARIF FADIL",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "544"
  },
  {
    "NAMA": "⁠MUHAMMAD TSAQIB HERSYA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
        "NOINFAQ": "297"
  },
  {
    "NAMA": "TRIYANA SAFITRI",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
            "NOINFAQ": "313"
  },
  {
    "NAMA": "RINDANG RIZKI ANANDA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
    "NOINFAQ": "361"
  },
  {
    "NAMA": "M. ALI ZABER",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
    "NOINFAQ": "290"
  },
  {
    "NAMA": "⁠RENDRA MAHARDIKA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID III",
        "NOINFAQ": "307"
  },
  {
    "NAMA": "NAYRA RAISA DINAR",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
          "NOINFAQ": "302"
  },
  {
    "NAMA": "AYANA MUKHBITA MARYAM",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "342"
  },
  {
    "NAMA": "RAYYA STARLA ADZKADINA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "511"
  },
  {
    "NAMA": "MUHAMMAD SAKHA AT THAHIR RAMADHAN",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "464"
  },
  {
    "NAMA": "HAVA HARAIDAN SAFIRA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "370"
  },
  {
    "NAMA": "AHMAD ZAINI DAHLAN",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "365"
  },
  {
    "NAMA": "RUSNI ADAM",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "310"
  },
  {
    "NAMA": "RAIHANA AINUN MARDIAH",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "306"
  },
  {
    "NAMA": "M. HAUFAN HAZZA ABQORY",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "536"

  },
  {
    "NAMA": "M. AZKA PUTRA",
    "PEMBIMBING AWAL": "USTADZAH EVI",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "462"
  },
  {
    "NAMA": "FEBRIYANI",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "353"
  },
  {
    "NAMA": "M. ALMAN. B",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH DINDA",
    "STATUS": "JILID II",
    "NOINFAQ": "354"
  },
  {
    "NAMA": "MUHAMMAD ARSHAD AL FATIH ASTADIWANGSA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "292"
  },
  {
    "NAMA": "RAFFA MULYATAMA SARAGIH",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "304"
  },
  {
    "NAMA": "ANDI ARSYILA HUMAIRA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "524"
  },
  {
    "NAMA": "ALMAIRA NURFAUZIAH",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH EVI",
    "STATUS": "JILID II",
    "NOINFAQ": "512"
  },
  {
    "NAMA": "RULITA AZZAHRA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH DIAH",
    "STATUS": "JILID II",
    "NOINFAQ": "506"
  },
  {
    "NAMA": "RAISYA NUR AQIFA NAYLA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "514"
  },
  {
    "NAMA": "NAILA AZKADINA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III"
  },
  {
    "NAMA": "NUR AMELIA NAZIHA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III",
    "NOINFAQ": "499"
  },
  {
    "NAMA": "FAYZA ANNISA FITRIA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ SYARIF",
    "STATUS": "JILID III"
  },
  {
    "NAMA": "AHMAD RAFFASYA ALFARIZI",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID III",
    "NOINFAQ": "500"
  },
  {
    "NAMA": "NUR AFIFAH",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID III"
  },
  {
    "NAMA": "M. FADILLAH RAMLAN",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID III",
    "NOINFAQ": "364"
  },
  {
    "NAMA": "MUHAMMAD YUSUF",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID III",
    "NOINFAQ": "497"
  },
  {
    "NAMA": "KIOSI ALTAF",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "273"
  },
  {
    "NAMA": "ZHAFIRA RASYIFA SALWA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "211"
  },
  {
    "NAMA": "SASKIA ANASTASYA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "477"
  },
  {
    "NAMA": "MUHAMMAD ZAIDAN RAHMAN",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "167"
  },
  {
    "NAMA": "PUTRI NABILA AZZAHRA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
    "NOINFAQ": "206"
  },
  {
    "NAMA": "FAUZIAH",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "209"
  },
  {
    "NAMA": "SITI AISYAH",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "170"
  },
  {
    "NAMA": "MUHAMMAD YUSUF RACHMAN",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "205"
  },
  {
    "NAMA": "HAFIDZAH AZZAHRA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZ THOHIR",
    "STATUS": "JILID VI",
    "NOINFAQ": "179"
  },
  {
    "NAMA": "AHMAD AL FARIZQI",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "265"
  },
  {
    "NAMA": "NAZIA ARSYIFA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "333"
  },
  {
    "NAMA": "ELSA RAIDA RAHMAWATI",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID VI",
    "NOINFAQ": "244"
  },
  {
    "NAMA": "KEYRA ANDITA BALQIS",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "323"
  },
  {
    "NAMA": "ARSY PUTRA FIRMANSYAH",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "231"
  },
  {
    "NAMA": "NADHIRA IMADINA ADIBA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "379"
  },
  {
    "NAMA": "AISHA ARSYIFA",
    "PEMBIMBING AWAL": "USTADZAH NISA",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID VI",
    "NOINFAQ": "268"
  },
  {
    "NAMA": "MUHAMMAD AL FATIH RAMADHAN",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "569"
  },
  {
    "NAMA": "ADELIA ZAHRATUSSHOFA",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "288"
  },
  {
    "NAMA": "M. REZA EFANSYAH",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "348"
  },
  {
    "NAMA": "MUHAMMAD HABIBIE",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "USTADZAH SANAH",
    "STATUS": "JILID IV",
    "NOINFAQ": "207"
  },
  {
    "NAMA": "ANISA AZAHRA",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "JUNI WARDANI",
    "STATUS": "JILID IV",
    "NOINFAQ": "285"
  },
  {
    "NAMA": "ALMEERA NURUL RASYADA",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "USTADZAH NISA",
    "STATUS": "JILID V",
    "NOINFAQ": "282"
  },
  {
    "NAMA": "AHMAD KEMAL REIS LIZUIRABIH",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V"
  },
  {
    "NAMA": "M.AZKA RIDLONI                ",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "USTADZAH SHALATIYAH",
    "STATUS": "JILID V",
        "NOINFAQ": "461"
  },
  {
    "NAMA": "AKHMAD HABIBIE",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "468"
  },
  {
    "NAMA": "MUHAMMAD NABIL ASY ARI",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
    "NOINFAQ": "494"
  },
  {
    "NAMA": "HAFI AHMAD SUBAKTI",
    "PEMBIMBING AWAL": "USTADZAH SHALATIYAH",
    "PEMBIMBING BARU": "USTADZ TAHMID",
    "STATUS": "JILID V",
        "NOINFAQ": "469"
  }
]

//hamburger menu
// Fungsi untuk mengubah tampilan menu pada perangkat mobile
document.getElementById('menu-toggle').onclick = function() {
    const mobileMenu = document.getElementById('mobile-menu');
    mobileMenu.classList.toggle('hidden'); // Menyembunyikan atau menampilkan menu
}
